### ISSUE TITLE
混淆打包后，运行报错

### ISSUE THREAD

**Issue by XuQK** [AlexLiuSheng/CheckVersionLib#102]
```java
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@d31dafd
versionCode=1
BOARD=hammerhead
BOOTLOADER=HHZ20h
TYPE=user
ID=M4B30X
TIME=1472688361000
BRAND=google
TAG=Build
SERIAL=068befde003c6e4e
HARDWARE=hammerhead
SUPPORTED_ABIS=[Ljava.lang.String;@ba183f2
CPU_ABI=armeabi-v7a
RADIO=M8974A-2.0.50.2.30
IS_DEBUGGABLE=false
MANUFACTURER=LGE
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@bfe4b54
TAGS=release-keys
CPU_ABI2=armeabi
UNKNOWN=unknown
USER=android-build
FINGERPRINT=google/hammerhead/hammerhead:6.0.1/M4B30X/3237893:user/release-keys
HOST=vpec7.mtv.corp.google.com
PRODUCT=hammerhead
versionName=1.0
DISPLAY=M4B30X
MODEL=Nexus 5
DEVICE=hammerhead
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.hulixuehui.app.data.a.l$a.Kk()' on a null object reference
	at com.hulixuehui.app.data.net.UpdateService.void onResponses(com.allenliu.versionchecklib.core.AVersionService,java.lang.String)(SourceFile:36)
	at com.allenliu.versionchecklib.core.AVersionService$1$1.void run()(SourceFile:93)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by XuQK** [comment]
不好意思，是我自己做了煞笔操作
