### ISSUE TITLE
(崩溃) 快速点击升级按钮，取消按钮

### ISSUE THREAD

**Issue by Colcode** [AlexLiuSheng/CheckVersionLib#181]
2.0.3 上出现这个崩溃 (2.0.8貌似修复了)
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ylteb.antlive/com.allenliu.versionchecklib.v2.ui.UIActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.allenliu.versionchecklib.v2.callback.CustomVersionDialogListener com.allenliu.versionchecklib.v2.builder.DownloadBuilder.getCustomVersionDialogListener()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2717)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2778)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1511)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6244)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:797)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.allenliu.versionchecklib.v2.callback.CustomVersionDialogListener com.allenliu.versionchecklib.v2.builder.DownloadBuilder.getCustomVersionDialogListener()' on a null object reference
	at com.allenliu.versionchecklib.v2.ui.UIActivity.showVersionDialog(UIActivity.java)
	at com.allenliu.versionchecklib.v2.ui.UIActivity.onCreate(Native Method)
	at android.app.Activity.performCreate(Activity.java:6731)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2670)

2.0.8 (崩溃)

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ylteb.antlive/com.allenliu.versionchecklib.v2.ui.UIActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.allenliu.versionchecklib.v2.builder.UIData com.allenliu.versionchecklib.v2.builder.DownloadBuilder.getVersionBundle()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2755)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2816)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1555)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.allenliu.versionchecklib.v2.builder.UIData com.allenliu.versionchecklib.v2.builder.DownloadBuilder.getVersionBundle()' on a null object reference
        at com.allenliu.versionchecklib.v2.ui.UIActivity.showDefaultDialog(UIActivity.java:66)
        at com.allenliu.versionchecklib.v2.ui.UIActivity.showVersionDialog(UIActivity.java:139)
        at com.allenliu.versionchecklib.v2.ui.UIActivity.onCreate(UIActivity.java:43)
        at android.app.Activity.performCreate(Activity.java:6871)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)

**Comment by yangsanning** [comment]
没有修复吧？我现在还遇到

**Comment by AlexLiuSheng** [comment]
2.1.5
