### ISSUE TITLE
UIActivity.showDefaultDialog()的时候DownloadBuilder为null

### ISSUE THREAD

**Issue by feimenggo** [AlexLiuSheng/CheckVersionLib#185]
`
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mozhe.mzcz/com.allenliu.versionchecklib.v2.ui.UIActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.allenliu.versionchecklib.v2.builder.UIData com.allenliu.versionchecklib.v2.builder.DownloadBuilder.getVersionBundle()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3194)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
	at android.app.ActivityThread.-wrap12(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.allenliu.versionchecklib.v2.builder.UIData com.allenliu.versionchecklib.v2.builder.DownloadBuilder.getVersionBundle()' on a null object reference
	at com.allenliu.versionchecklib.v2.ui.UIActivity.showDefaultDialog(Unknown Source:2)
	at com.allenliu.versionchecklib.v2.ui.UIActivity.showVersionDialog(Unknown Source:20)
	at com.allenliu.versionchecklib.v2.ui.UIActivity.onCreate(Native Method)
	at android.app.Activity.performCreate(Activity.java:7372)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147)
	... 9 more
java.lang.NullPointerException: Attempt to invoke virtual method 'com.allenliu.versionchecklib.v2.builder.UIData com.allenliu.versionchecklib.v2.builder.DownloadBuilder.getVersionBundle()' on a null object reference
	at com.allenliu.versionchecklib.v2.ui.UIActivity.showDefaultDialog(Unknown Source:2)
	at com.allenliu.versionchecklib.v2.ui.UIActivity.showVersionDialog(Unknown Source:20)
	at com.allenliu.versionchecklib.v2.ui.UIActivity.onCreate(Native Method)
	at android.app.Activity.performCreate(Activity.java:7372)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
	at android.app.ActivityThread.-wrap12(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
`

**Comment by 3277076046** [comment]
我也碰到这个问题了，在一个App上好好的，搬到另一个App上就报这个错，请教找到原因了吗？？？

**Comment by lijie110** [comment]
服务被杀死导致空指针问题，开个服务处理这个是不是有问题

**Comment by AlexLiuSheng** [comment]
这个问题比较棘手，试试2.1.1

**Comment by wangou** [comment]
这个问题解决了吗？我也碰到了。

**Comment by AlexLiuSheng** [comment]
2.1.5
