### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by wanchunyang** [AlexLiuSheng/CheckVersionLib#203]
2018-11-20 15:56:03 Version Code:2 OS version:8.0.0_26 Vendor:HUAWEI Model:LON-AL00 CPU ABI:armeabi-v7 java.lang.NullPointerException: Attempt to invoke virtual method 'com.allenliu.versionchecklib.v2.builder.RequestVersionBuilder com.allenliu.versionchecklib.v2.builder.DownloadBuilder.getRequestVersionBuilder()' on a null object reference 	at com.allenliu.versionchecklib.v2.ui.VersionService.checkWhetherNeedRequestVersion(VersionService.java:181) 	at com.allenliu.versionchecklib.v2.ui.VersionService.onHandleWork(VersionService.java:108) 	at com.allenliu.versionchecklib.v2.ui.VersionService$5.run(VersionService.java:360)

**Comment by liuxiangteng** [comment]
我也会报这个错误

**Comment by AlexLiuSheng** [comment]
哪个版本

**Comment by liuxiangteng** [comment]
1
java.lang.NullPointerException
2
    at com.allenliu.versionchecklib.v2.ui.VersionService$2.run(VersionService.java:158)
3
    at android.os.Handler.handleCallback(Handler.java:733)
4
    at android.os.Handler.dispatchMessage(Handler.java:95)
5
    at android.os.Looper.loop(Looper.java:136)
6
    at android.app.ActivityThread.main(ActivityThread.java:5111)
7
    at java.lang.reflect.Method.invokeNative(Native Method)
8
    at java.lang.reflect.Method.invoke(Method.java:515)
9
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
10
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
11
    at dalvik.system.NativeStart.main(Native Method)

**Comment by liuxiangteng** [comment]
老铁   您看这个报错能想到是啥问题吗

**Comment by AlexLiuSheng** [comment]
是偶发性的还是一直存在，有没有开启混淆

**Comment by AlexLiuSheng** [comment]
是偶发性的还是一直存在，有没有开启混淆

**Comment by wanchunyang** [comment]
> 
> 
> 是偶发性的还是一直存在，有没有开启混淆

看起来是多线程引起的 new thread（）那儿
我这边的复现步骤是 重复点击升级（手速比较快） 底层调用的你写的库
手速快就是必现

**Comment by liuxiangteng** [comment]
偶发性的

**Comment by liuxiangteng** [comment]
设备机型N958St       系统版本4.4.4
统计出来的是在这个机器上 会经常报那个错误

**Comment by AlexLiuSheng** [comment]
implementation 'com.allenliu.versionchecklib:library:2.1.4'
帮我测试下问题解决下没有

**Comment by liuxiangteng** [comment]
我那也是用户使用出来报错的  我自己没复现  等我统计到还有错误的话  再跟你说

**Comment by AlexLiuSheng** [comment]
好的

**Comment by AlexLiuSheng** [comment]
先关闭 有问题再打开
