### ISSUE TITLE
版本2.1.5在集成时提示错误No static field abc_ic_ab_back_mtrl_am_alpha

### ISSUE THREAD

**Issue by KangCaijun** [AlexLiuSheng/CheckVersionLib#207]
编译没有错，运行时报错：
java.lang.NoSuchFieldError: No static field abc_ic_ab_back_mtrl_am_alpha of type I in class Landroid/support/v7/appcompat/R$drawable; or its superclasses (declaration of 'android.support.v7.appcompat.R$drawable' appears in /data/app/com.oyunchaq.gamebox-1TMGcCj98qr6hK1dOBabWg==/base.apk)
        at android.support.v7.widget.AppCompatDrawableManager.<clinit>(AppCompatDrawableManager.java:116)
        at android.support.v7.widget.AppCompatDrawableManager.get(AppCompatDrawableManager.java:79)
        at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:59)
        at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:53)
        at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:106)
        at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:980)
        at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1039)
        at android.support.v4.view.LayoutInflaterCompat$Factory2Wrapper.onCreateView(LayoutInflaterCompat.java:55)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:783)

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.3"
    defaultConfig {
        applicationId "com.oyunchaq.gamebox"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 33
        versionName "1.82"

dependencies {
//    compile 'com.android.support:appcompat-v7:23.2.0'
//    compile 'com.android.support:appcompat-v7:27.1.1'
//    compile 'com.android.support.constraint:constraint-layout:1.1.2'
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.squareup.okhttp3:okhttp:3.9.1'
    compile "com.google.code.gson:gson:2.8.0"
    compile 'com.allenliu.versionchecklib:library:2.1.5'
    testCompile 'junit:junit:4.12'

我已经去掉了项目本身的依赖，直接使用库依赖了，还是没法解决

**Comment by AlexLiuSheng** [comment]
appcompat版本问题
