### ISSUE TITLE
版本2.1.5空指针报错

### ISSUE THREAD

**Issue by kpioneer123** [AlexLiuSheng/CheckVersionLib#213]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.allenliu.versionchecklib.v2.builder.UIData com.allenliu.versionchecklib.v2.builder.DownloadBuilder.getVersionBundle()' on a null object reference
at com.allenliu.versionchecklib.v2.ui.UIActivity.showDefaultDialog(UIActivity.java)
at com.allenliu.versionchecklib.v2.ui.UIActivity.showVersionDialog(UIActivity.java)
at com.allenliu.versionchecklib.v2.ui.UIActivity.onCreate(Native Method)
at android.app.Activity.performCreate(Activity.java:6850)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2818)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2940)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1663)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:159)
at android.app.ActivityThread.main(ActivityThread.java:6385)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)

**Comment by AlexLiuSheng** [comment]
2.1.7
