### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by liuxiangteng** [AlexLiuSheng/CheckVersionLib#221]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.paiba.app000004/com.allenliu.versionchecklib.v2.ui.DownloadingActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.allenliu.versionchecklib.v2.callback.ForceUpdateListener com.allenliu.versionchecklib.v2.builder.DownloadBuilder.getForceUpdateListener()' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2954)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1733)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:192)
at android.app.ActivityThread.main(ActivityThread.java:6795)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:817)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.allenliu.versionchecklib.v2.callback.ForceUpdateListener com.allenliu.versionchecklib.v2.builder.DownloadBuilder.getForceUpdateListener()' on a null object reference
at com.allenliu.versionchecklib.v2.ui.DownloadingActivity.showDefaultDialog(Unknown Source:38)
at com.allenliu.versionchecklib.v2.ui.DownloadingActivity.showLoadingDialog(Unknown Source:34)
at com.allenliu.versionchecklib.v2.ui.DownloadingActivity.onCreate(Unknown Source:8)
at android.app.Activity.performCreate(Activity.java:7112)
at android.app.Activity.performCreate(Activity.java:7103)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2907)
... 9 more
java.lang.NullPointerException: Attempt to invoke virtual method 'com.allenliu.versionchecklib.v2.callback.ForceUpdateListener com.allenliu.versionchecklib.v2.builder.DownloadBuilder.getForceUpdateListener()' on a null object reference
at com.allenliu.versionchecklib.v2.ui.DownloadingActivity.showDefaultDialog(Unknown Source:38)
at com.allenliu.versionchecklib.v2.ui.DownloadingActivity.showLoadingDialog(Unknown Source:34)
at com.allenliu.versionchecklib.v2.ui.DownloadingActivity.onCreate(Unknown Source:8)
at android.app.Activity.performCreate(Activity.java:7112)
at android.app.Activity.performCreate(Activity.java:7103)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2907)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1733)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:192)
at android.app.ActivityThread.main(ActivityThread.java:6795)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:817)

**Comment by AlexLiuSheng** [comment]
2.1.7么

**Comment by liuxiangteng** [comment]
是的。看我发的另一个issue 那个出现的多一点

**Comment by OsbornWJ** [comment]
> 2.1.7么

我这边也出现了这个问题，是static的原因吗
![qq 20190117134354](https://user-images.githubusercontent.com/18139366/51298060-f66b0400-1a5d-11e9-8430-17191c7eee6b.png)

**Comment by OsbornWJ** [comment]
如果出现内存不足，这个对象会被回收吧

**Comment by AlexLiuSheng** [comment]
这个问题一直没找到原因，我估计是异步回调回来builder已经为空了，但是我没出过这个问题并且在service销毁的时候会清除所有的异步任务，除了static 感觉没什么更好的方法去传递，序列化存储传递因为有接口所以也不可行。
可以试试最新版吧，destory的时候没有清空builder
