### ISSUE TITLE
Can only use lower 8 bits for requestCode

### ISSUE THREAD

**Issue by w2cCG** [AlexLiuSheng/CheckVersionLib#224]
MY_PERMISSIONS_REQUEST_WRITE_EXTERNAL_STORAGE 用到了前8个bit，造成挂起，请问如何解决？

ActivityCompat.requestPermissions(this,
                        new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE},
                        MY_PERMISSIONS_REQUEST_WRITE_EXTERNAL_STORAGE);

public static final int MY_PERMISSIONS_REQUEST_WRITE_EXTERNAL_STORAGE = 0x123;

 
//异常信息如下：
Process: com.ispring.gameplane, PID: 15395
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ispring.gameplane/com.allenliu.versionchecklib.core.PermissionDialogActivity}: java.lang.IllegalArgumentException: Can only use lower 8 bits for requestCode
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2740)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2801)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1540)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6358)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:799)
     Caused by: java.lang.IllegalArgumentException: Can only use lower 8 bits for requestCode
        at android.support.v4.app.FragmentActivity.validateRequestPermissionsRequestCode(FragmentActivity.java:763)
        at android.support.v4.app.ActivityCompatApi23.requestPermissions(ActivityCompat23.java:29)
        at android.support.v4.app.ActivityCompat.requestPermissions(ActivityCompat.java:316)
        at com.allenliu.versionchecklib.core.PermissionDialogActivity.onCreate(PermissionDialogActivity.java:47)

**Comment by AlexLiuSheng** [comment]
1.+的版本已经停止维护，请使用最新版
