### ISSUE TITLE
8.0系统 崩溃

### ISSUE THREAD

**Issue by xuzhiyong017** [AlexLiuSheng/CheckVersionLib#231]
2019-01-28 18:05:41.191 5904-5904/com.smartcity.helper E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.smartcity.helper, PID: 5904
    android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{33cf52b u0 com.smartcity.helper/com.allenliu.versionchecklib.v2.ui.VersionService}
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2082)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7536)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by xuzhiyong017** [comment]
启动服务就挂了，跳转到versionService

**Comment by xuzhiyong017** [comment]
> 版本
找到问题了，已经解决了。是因为我在失败的情况下加了重试，重试，重试没有间隔。导致短时间多次启动service导致报错，我现在是每次重试先stopService 延时之后再启动更新流程

**Comment by sduqlsc** [comment]
> 版本
同样错误，@AlexLiuSheng 2.1.9出错，但是2.0.5不报错
