### ISSUE TITLE
最新2.2.0空指针报错红米手机上面出的问题

### ISSUE THREAD

**Issue by liuteng159753** [AlexLiuSheng/CheckVersionLib#264]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.Ringtone.play()' on a null object reference
	at com.allenliu.versionchecklib.v2.ui.NotificationHelper.createNotification(NotificationHelper.java:154)
	at com.allenliu.versionchecklib.v2.ui.NotificationHelper.showNotification(NotificationHelper.java:74)
	at com.allenliu.versionchecklib.v2.ui.VersionService$1.onCheckerStartDownload(VersionService.java:262)
	at com.allenliu.versionchecklib.v2.net.DownloadMangerV2$1.run(DownloadMangerV2.java:36)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5845)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)

**Comment by liuteng159753** [comment]
请问大神怎么解决哇。

**Comment by 920651004** [comment]
请问这个问题解决了么 @liuteng159753
