### ISSUE TITLE
在华为P20手机上出现解析包异常

### ISSUE THREAD

**Issue by shmilx** [AlexLiuSheng/CheckVersionLib#266]
2019-07-29 18:41:22.584 4401-4419/? E/DatabaseUtils: Writing exception to parcel
    java.lang.SecurityException: Permission Denial: reading android.support.v4.content.FileProvider uri content://com.anshushuziyiliao.data.FileProvider/rc_external_path/anshu/apk/com.anshushuziyiliao.data.apk from pid=3765, uid=10042 requires the provider be exported, or grantUriPermission()
        at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:663)
        at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:532)
        at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:523)
        at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:451)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:302)
        at android.os.Binder.execTransact(Binder.java:739)

**Comment by shmilx** [comment]
/**
     * 强制更新操作
     * 通常关闭整个activity所有界面，这里方便测试直接关闭当前activity
     */
    private void forceUpdate() {
        CustomToast.showToast(MainActivitys.this, "请更新后使用", 1500);
        finish();
    }
我的问题在这个里面 这样写 就解决了。
之前  System.exit(0);在里面加了这样一句话

**Comment by shmilx** [comment]
总结 就是 还没跳转到 允许未知来源  界面   app 就杀死  没跳转过去

**Comment by a465855787** [comment]
这个真的是多谢了，完美的解决了我的问题。
