### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by AndroidXinDong** [AlexLiuSheng/CheckVersionLib#277]
java.lang.RuntimeException: Unable to create service com.allenliu.versionchecklib.v2.ui.VersionService: org.greenrobot.eventbus.EventBusException: Subscriber class com.allenliu.versionchecklib.v2.ui.VersionService and its super classes have no public methods with the @Subscribe annotation
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3568)
        at android.app.ActivityThread.-wrap4(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1812)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
     Caused by: org.greenrobot.eventbus.EventBusException: Subscriber class com.allenliu.versionchecklib.v2.ui.VersionService and its super classes have no public methods with the @Subscribe annotation
        at org.greenrobot.eventbus.o.a(Unknown Source:60)
        at org.greenrobot.eventbus.c.a(Unknown Source:6)

**Comment by AndroidXinDong** [comment]
debug的时候能够正常运行，一旦打包之后 程序运行到这里就会崩溃，之前一直都好好的，最近软件版本升级的时候出了这个问题，请问大神这个是出了什么问题，我加上eventbus的注册监听也是不行

**Comment by AlexLiuSheng** [comment]
混淆问题

**Comment by AndroidXinDong** [comment]
谢谢您的快速回复，我应该去除哪一部分的混淆

**Comment by AlexLiuSheng** [comment]
-keepattributes Annotation
-keepclassmembers class ** {
@org.greenrobot.eventbus.Subscribe ;
}
-keep enum org.greenrobot.eventbus.ThreadMode { ; }
-keepclassmembers class * extends org.greenrobot.eventbus.util.ThrowableFailureEvent {
(java.lang.Throwable);
}
-keep class com.allenliu.versionchecklib.**{;}

**Comment by AndroidXinDong** [comment]
AlexLiuSheng，混淆是不是也有问题， -keepclassmembers class * {    @org.greenrobot.eventbus.Subscribe; }这句 编译的时候 报 Expecting java type before ';'

**Comment by AndroidXinDong** [comment]
修改成： -keepclassmembers class ** {    @org.greenrobot.eventbus.Subscribe **<methods>**;}
-keepclassmembers class * extends org.greenrobot.eventbus.util.ThrowableFailureEvent {    **<init>**(java.lang.Throwable);}
编译成功 ，如有不对请您指正，再次感谢您的答疑解惑

**Comment by AndroidXinDong** [comment]
修改成：method 和 init显示不出来，上图吧
![微信截图_20190923101130](https://user-images.githubusercontent.com/19897407/65398569-91d12780-ddea-11e9-9028-d8730ecd73ca.png)

编译成功 ，如有不对请您指正，再次感谢您的答疑解惑

**Comment by AlexLiuSheng** [comment]
已更新文档
