### ISSUE TITLE
android 10.0 下载失败是否重试 androidx

### ISSUE THREAD

**Issue by zhongdevin** [AlexLiuSheng/CheckVersionLib#309]
java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
        at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:149)
        at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1702)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1518)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1435)
        at android.media.MediaPlayer.attemptDataSource(MediaPlayer.java:1154)
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1103)
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1019)
        at android.media.Ringtone.setUri(Ringtone.java:332)
        at android.media.RingtoneManager.getRingtone(RingtoneManager.java:728)
        at android.media.RingtoneManager.getRingtone(RingtoneManager.java:703)
        at android.media.RingtoneManager.getRingtone(RingtoneManager.java:666)
        at com.allenliu.versionchecklib.v2.ui.NotificationHelper.createNotification(NotificationHelper.java:154)
        at com.allenliu.versionchecklib.v2.ui.NotificationHelper.showNotification(NotificationHelper.java:75)
        at com.allenliu.versionchecklib.v2.ui.VersionService$2.onCheckerStartDownload(VersionService.java:275)
        at com.allenliu.versionchecklib.v2.net.DownloadMangerV2$1.run(DownloadMangerV2.java:35)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by f2424225711** [comment]
这个怎么解决呢，oppo手机也出现这样提示
