### ISSUE TITLE
请教下打包混淆有错误：

### ISSUE THREAD

**Issue by yuxi567** [AlexLiuSheng/CheckVersionLib#314]
java.lang.RuntimeException: Job failed, see logs for details
	at com.android.build.gradle.internal.transforms.ProGuardTransform.transform(ProGuardTransform.java:207)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)

**Comment by yuxi567** [comment]
更新版本2.3.4_appcompat，打包提示的？
