### ISSUE TITLE
空指针异常

### ISSUE THREAD

**Issue by lihaodong** [AlexLiuSheng/CheckVersionLib#333]
**版本:com.github.AlexLiuSheng:CheckVersionLib:2.4_androidx**
--logversion:utracea
Process Name: &#39;&#39;
Thread Name: &#39;main&#39;
Back traces starts.
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.allenliu.versionchecklib.v2.ui.DownloadingActivity}: java.lang.NullPointerException: Attempt to invoke virtual method &#39;com.allenliu.versionchecklib.v2.callback.ForceUpdateListener com.allenliu.versionchecklib.v2.builder.DownloadBuilder.getForceUpdateListener()&#39; on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3143)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3278)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2012)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:243)
	at android.app.ActivityThread.main(ActivityThread.java:7096)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method &#39;com.allenliu.versionchecklib.v2.callback.ForceUpdateListener com.allenliu.versionchecklib.v2.builder.DownloadBuilder.getForceUpdateListener()&#39; on a null object reference
	at com.allenliu.versionchecklib.v2.ui.DownloadingActivity.showDefaultDialog(DownloadingActivity.java:74)
	at com.allenliu.versionchecklib.v2.ui.DownloadingActivity.showLoadingDialog(DownloadingActivity.java:160)
	at com.allenliu.versionchecklib.v2.ui.DownloadingActivity.onCreate(DownloadingActivity.java:33)
	at android.app.Activity.performCreate(Activity.java:7267)
	at android.app.Activity.performCreate(Activity.java:7258)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3123)
	... 11 more
Back traces ends.

**Comment by hijamoya** [comment]
Same issue here!

**Comment by AlexLiuSheng** [comment]
2.4.1
