### ISSUE TITLE
检测出anr目前没有头绪，大佬帮忙看下吧

### ISSUE THREAD

**Issue by caopeng000** [AlexLiuSheng/CheckVersionLib#340]

**Comment by caopeng000** [comment]
OkHttp https://p.ampmake.com/..." prio=5 tid=145 Blocked
  | group="main" sCount=1 dsCount=0 obj=0x13cf3820 self=0xb0eafe00
  | sysTid=26813 nice=0 cgrp=default sched=0/0 handle=0x97e30920
  | state=S schedstat=( 36692868470 674997751 14475 ) utm=3307 stm=362 core=5 HZ=100
  | stack=0x97d2e000-0x97d30000 stackSize=1038KB
  | held mutexes=
  at android.os.MessageQueue.enqueueMessage(MessageQueue.java:541)
  - waiting to lock <0x0c1606eb> (a android.os.MessageQueue) held by thread 1
  at android.os.Handler.enqueueMessage(Handler.java:643)
  at android.os.Handler.sendMessageAtTime(Handler.java:612)
  at android.os.Handler.sendMessageDelayed(Handler.java:582)
  at android.os.Handler.post(Handler.java:338)
  at com.allenliu.versionchecklib.core.http.FileCallBack.onResponse(FileCallBack.java:15)
  at okhttp3.RealCall$AsyncCall.execute(RealCall.java:5)
  at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:3)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
  at java.lang.Thread.run(Thread.java:761)
