### ISSUE TITLE
android10  突然不能更新

### ISSUE THREAD

**Issue by yuanduyua** [AlexLiuSheng/CheckVersionLib#351]
com.allenliu.versionchecklib:library:2.1.9   前两天还可以  有什么更新吗

**Comment by yuanduyua** [comment]
E/Allen Checker: downloadPath:/storage/emulated/0/AllenVersionPath/com.education.silegao.silegaoeducation.apk
2021-12-01 17:32:12.432 10556-10556/com.education.silegao.silegaoeducation E/EventBus: Could not dispatch event: class com.allenliu.versionchecklib.v2.eventbus.CommonEvent to subscribing class class com.allenliu.versionchecklib.v2.ui.VersionService
    java.lang.IllegalStateException: Unable to extract the trust manager on Android10Platform, sslSocketFactory is class com.android.org.conscrypt.OpenSSLSocketFactoryImpl
        at okhttp3.internal.platform.Platform.buildCertificateChainCleaner(Platform.kt:152)
        at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.kt:737)
        at com.allenliu.versionchecklib.core.http.AllenHttp.getHttpClient(AllenHttp.java:39)
        at com.allenliu.versionchecklib.v2.net.DownloadMangerV2.download(DownloadMangerV2.java:40)
        at com.allenliu.versionchecklib.v2.ui.VersionService.startDownloadApk(VersionService.java:286)
        at com.allenliu.versionchecklib.v2.ui.VersionService.receiveEvent(VersionService.java:351)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:510)
        at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:437)
        at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:414)
        at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:387)
        at org.greenrobot.eventbus.EventBus.post(EventBus.java:268)
        at com.allenliu.versionchecklib.core.PermissionDialogActivity.sendBroadcast(PermissionDialogActivity.java:80)
        at com.allenliu.versionchecklib.core.PermissionDialogActivity.onCreate(PermissionDialogActivity.java:56)
        at android.app.Activity.performCreate(Activity.java:8085)
        at android.app.Activity.performCreate(Activity.java:8073)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3870)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4076)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)

**Comment by yuanduyua** [comment]
大佬  有办法能解决吗

**Comment by yuanduyua** [comment]
急急急
