### ISSUE TITLE
Android studio2.3 升级到3.0，运行时错误：Unable to get provider com.allenliu.versionchecklib.core.VersionFileProvider:

### ISSUE THREAD

**Issue by awsyawsa** [AlexLiuSheng/CheckVersionLib#57]
帮忙看一下，这个问题怎么处理吧。异常信息如下：java.lang.RuntimeException: Unable to get provider com.allenliu.versionchecklib.core.VersionFileProvider: java.lang.ClassNotFoundException: com.allenliu.versionchecklib.core.VersionFileProvider
                                                               at android.app.ActivityThread.installProvider(ActivityThread.java:4563)
                                                               at android.app.ActivityThread.installContentProviders(ActivityThread.java:4190)
                                                               at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4132)
                                                               at android.app.ActivityThread.access$1300(ActivityThread.java:130)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
                                                               at android.os.Handler.dispatchMessage(Handler.java:99)
                                                               at android.os.Looper.loop(Looper.java:137)
                                                               at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                               at java.lang.reflect.Method.invoke(Method.java:511)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run

**Comment by asunicom** [comment]
这问题怎么解决的？

**Comment by asunicom** [comment]
我是在android 4.3上发现的问题。5.0以上暂时没问题

**Comment by AlexLiuSheng** [comment]
贴下启动代码 我看看

**Comment by asunicom** [comment]
不是启动的问题。及时不启动，只引入包也会出错。 目前只发现android 4.3的三星note3 出问题。

**Comment by 454464335** [comment]
遇到这个问题，有已经解决的吗。求支招

**Comment by somesoon** [comment]
我在4.4.4的魅族上遇到这个问题

**Comment by zhangliangnbu** [comment]
multidex的问题，sdk < 21 会遇到这样的问题，官网的解决方案：

Setting up your app project to use a multidex configuration requires that you make the following modifications to your app project, depending on the minimum Android version your app supports.

If your minSdkVersion is set to 21 or higher, all you need to do is set multiDexEnabled to true in your module-level build.gradle file, as shown here:

```
android {
    defaultConfig {
        ...
        minSdkVersion 21 
        targetSdkVersion 26
        multiDexEnabled true
    }
    ...
}
```
However, if your minSdkVersion is set to 20 or lower, then you must use the multidex support library as follows:

Modify the module-level build.gradle file to enable multidex and add the multidex library as a dependency, as shown here:
```
android {
    defaultConfig {
        ...
        minSdkVersion 15 
        targetSdkVersion 26
        multiDexEnabled true
    }
    ...
}

dependencies {
  compile 'com.android.support:multidex:1.0.1'
}
```

Depending on whether you override the Application class, perform one of the following:
If you do not override the Application class, edit your manifest file to set android:name in the <application> tag as follows:

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.myapp">
    <application
            android:name="android.support.multidex.MultiDexApplication" >
        ...
    </application>
</manifest>
```

If you do override the Application class, change it to extend MultiDexApplication (if possible) as follows:

```
public class MyApplication extends MultiDexApplication { ... }
```
Or if you do override the Application class but it's not possible to change the base class, then you can instead override the attachBaseContext() method and call MultiDex.install(this) to enable multidex:
```
public class MyApplication extends SomeOtherApplication {
  @Override
  protected void attachBaseContext(Context base) {
     super.attachBaseContext(base);
     MultiDex.install(this);
  }
}
```

具体请见官网：https://developer.android.com/studio/build/multidex.html#dev-build

**Comment by AlexLiuSheng** [comment]
V1版停止维护
