### ISSUE TITLE
 Only fullscreen opaque activities can request orientation

### ISSUE THREAD

**Issue by smccjj** [AlexLiuSheng/CheckVersionLib#63]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zhongfu.upop.debug/com.allenliu.versionchecklib.core.PermissionDialogActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3173)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3268)
                                                                            at android.app.ActivityThread.-wrap12(Unknown Source:0)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1880)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:108)
                                                                            at android.os.Looper.loop(Looper.java:166)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7358)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:926)
                                                                         Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
                                                                            at android.app.Activity.onCreate(Activity.java:1076)
                                                                            at android.support.v4.app.SupportActivity.onCreate(SupportActivity.java:66)
                                                                            at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:297)
                                                                            at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84)
                                                                            at com.allenliu.versionchecklib.core.PermissionDialogActivity.onCreate(PermissionDialogActivity.java:20)
                                                                            at android.app.Activity.performCreate(Activity.java:7330)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3126)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3268) 
                                                                            at android.app.ActivityThread.-wrap12(Unknown Source:0) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1880) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:108) 
                                                                            at android.os.Looper.loop(Looper.java:166) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7358) 

机型：华为mate10 系统版本android 8.0

**Comment by AlexLiuSheng** [comment]
你项目targetSdkVersion 是27么？

**Comment by AlexLiuSheng** [comment]
compile 'com.allenliu.versionchecklib:library:1.7.7'

**Comment by qianlvable** [comment]
https://github.com/aosp-mirror/platform_frameworks_base/commit/39791594560b2326625b663ed6796882900c220f#diff-960c6fdd4a4b336d98b785268b2a78ff android8.0的这个变更导致的，非全屏Activity不能直接设置屏幕的方向
