### ISSUE TITLE
点击下载的时候报错了

### ISSUE THREAD

**Issue by ZHOUCHAOzzz** [AlexLiuSheng/CheckVersionLib#95]
01-02 13:02:07.102 22904-22904/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.hxkj.schoolwindow, PID: 22904
                                                   java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Ljava/lang/String;)V in class Landroid/support/v4/app/NotificationCompat$Builder; or its super classes (declaration of 'android.support.v4.app.NotificationCompat$Builder' appears in /data/app/com.hxkj.schoolwindow-1/split_lib_dependencies_apk.apk)
                                                       at com.allenliu.versionchecklib.core.DownloadManager.createNotification(DownloadManager.java:237)
                                                       at com.allenliu.versionchecklib.core.DownloadManager.downloadAPK(DownloadManager.java:89)
                                                       at com.allenliu.versionchecklib.core.VersionDialogActivity.downloadFile(VersionDialogActivity.java:261)
                                                       at com.allenliu.versionchecklib.core.VersionDialogActivity.requestPermissionAndDownloadFile(VersionDialogActivity.java:296)
                                                       at com.allenliu.versionchecklib.core.VersionDialogActivity.dealAPK(VersionDialogActivity.java:251)
                                                       at com.allenliu.versionchecklib.core.VersionDialogActivity$2.onClick(VersionDialogActivity.java:149)
                                                       at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:161)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:163)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6276)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:788)
01-02 13:02:07.201 1864-2084/? E/InputDispatcher: channel '198ca6c com.hxkj.schoolwindow/com.hxkj.schoolwindow.ui.act.Act_

**Comment by AlexLiuSheng** [comment]
应该是 V7包版本  BuildToolVersion compileSdkVersion 不统一的问题

**Comment by renhuan2015** [comment]
这个怎么解决

**Comment by renhuan2015** [comment]
这个怎么解决的啊

**Comment by xchz** [comment]
@AlexLiuSheng 我已经把项目里所有的buildToolsVersion和compileSdkVersion改成一致了是'25.4.0'，还是报这个错....但是改成27.1.1就没问题了，可是我的项目里其他库就又出问题了...搞了一天了，咋办呀大佬

**Comment by xchz** [comment]
@AlexLiuSheng 
出问题的代码: `builder = new NotificationCompat.Builder(context, CHANNEL_ID);`
我看了support-compat-25.4.0版本代码NotificationCompat.Builder确实只有一个参数的构造函数啊。。。

**Comment by xchz** [comment]
找到问题了`NotificationCompat.Builder(context, CHANNEL_ID)`这个构造函数是api26之后才有的，简直了.........

**Comment by AlexLiuSheng** [comment]
@xchz 讲真的你不说我还不知道 ，请大家尽量用最新版support把
